[project]
name = "genomics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "category-encoders>=2.9.0",
    "ipykernel>=7.2.0",
    "pandas>=3.0.0",
    "pybioportal>=1.0.1",
]
